### ISSUE TITLE
nvidia-persistenced keeps it's username after remove

### ISSUE THREAD

**Issue by mhsabbagh** [NVIDIA/nvidia-persistenced#1]
Hello.

in Ubuntu 13.04, when installing nvidia-persistenced, and removeing it agian.
it keeps the username "nvidia-persistenced-daemon" in the system and it doesn't remove it, this cause some problems when remastering the local system in some tools like Remastersys or Relinux.. because nvidia-persistenced uid is 999.

the fix is just to run this command automatically after package removal:
$ sudo userdel nvidia-persistenced

so, is there anyway to do this by default in nvidia-persistenced instead of doing it manually?

thanks.

**Comment by aaronp24** [comment]
Closing, since this sounds like a downstream packaging bug.

There's an init/install.sh in the repository that will useradd or userdel a nvidia-persistenced user as necessary. Please open a separate issue if you're using that and it's not working.
