### ISSUE TITLE
Release for 525.85.12

### ISSUE THREAD

**Issue by henryli001** [NVIDIA/nvidia-persistenced#9]
Hi,

I don't see a release for v525.85.12. Is there a reason why this version is not supported?

**Comment by aaronp24** [comment]
I only push the tool sources for UDA drivers that appear on https://download.nvidia.com/XFree86/Linux-x86_64/ and https://www.nvidia.com/en-us/drivers/unix/linux-amd64-display-archive/ . Drivers released outside of that process aren't included.
